services:
  pokemon-csv-app:
    container_name: pokemon-csv-app
    build:
      context: .
      dockerfile: docker/dockerfile.dev.yml
    command: npm run start:dev
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3000:3000'
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    depends_on:
      - pokemon-csv-redis

  pokemon-csv-redis:
    container_name: pokemon-csv-redis
    image: redis:7
    ports:
      - '6379:6379'
    volumes:
      - redis:/data
volumes:
  redis:
